### ISSUE TITLE
Problem: zbroker does not daemonize

### ISSUE THREAD

**Issue by rpedde** [zeromq/zbroker#13]
zbroker should be able to be run as either a daemon or a foreground application, so as to interface better with the various init styles.

**Comment by hintjens** [comment]
Any preference on how to handle stdout/stderr? I've got code working, which
sets these to /dev/null so the daemon is totally silent unless it sends
stuff to syslog etc.

**Comment by hintjens** [comment]
OK, done. The code is in czmq/zsys.c:zsys_daemonize(). Will need master of CZMQ.

**Comment by hintjens** [comment]
Run this using zbroker -b
