### ISSUE TITLE
Problem: zpipes_client_write allows write on closed reader

### ISSUE THREAD

**Issue by rpedde** [zeromq/zbroker#16]
on a named pipe, writing against a read-side close file handle results in SIGPIPE, and -1/EBADF.  zpipes_client_write should probably return ssize_t with -1 on error.

**Comment by hintjens** [comment]
OK, fixed, as far as I understand it. The client API doesn't expose closed file handlers (as it destroys the object at the same time). However it allowed a write on a read handle. This is now trapped and returned as a EBADF error.

**Comment by rpedde** [comment]
Yeah, you got what I was looking at despite my bad commentary.  :)
