### ISSUE TITLE
Problem: zbroker blows up on unexpected message replies

### ISSUE THREAD

**Issue by rpedde** [zeromq/zbroker#17]
s_expect_reply asserts on zpipes_msg_id(reply) == message_id.  This likely should instead tear down the pipe and allow the calling read/write function the ability to pass back an error condition.

**Comment by hintjens** [comment]
Fixed.

**Comment by hintjens** [comment]
Sorry, didn't mean to close. This is the same as #15, and fixed by that pull request.

**Comment by rpedde** [comment]
Looks good.  Thanks.
