### ISSUE TITLE
Problem: client potentially loses data

### ISSUE THREAD

**Issue by rpedde** [zeromq/zbroker#22]
If the buffer provided by a client is smaller than the size of the pending data chunk, the excess data in the chunk is thrown away.

The client read function really needs to keep an offset of the position of the current chunk, and continue to serve from it until the chunk is exhausted.

In a perfect world, we'd never return short reads, either.  Reads shorter then requested size happen, but are surprising unless at end of file, I think.  So a single read in excess of the pending chunk size should probably continue to pull chunks until the client supplied buffer is full.

This might be something better deferred to after the raw client re-write, though.  Just noting this for posterity.

**Comment by hintjens** [comment]
Are we agreed that the API should deliver a stream, not chunks?

**Comment by rpedde** [comment]
I think from the client perspective, it should be a stream, yes.

**Comment by hintjens** [comment]
OK, that's clear, thanks.

**Comment by hintjens** [comment]
Closing this and replacing with #24.
