### ISSUE TITLE
Feature request: configurable logging

### ISSUE THREAD

**Issue by rpedde** [zeromq/zbroker#51]
It would be nice to be able to change animate logging via configuration rather than compilation.

Honoring SIGHUP for config re-read would be useful as well.  

In some kind of far-future super utopian world, a command-line client that talked the management protocol to push a single setting into a running server would be great.  :)

**Comment by hintjens** [comment]
Split into #57 and #58. 

Remote config and admin is definitely important. We did a lot of this in OpenAMQ.
