### ISSUE TITLE
Problem: libzmtp stack does not connect

### ISSUE THREAD

**Issue by hintjens** [zeromq/zbroker#69]
In https://github.com/hintjens/zbroker/commit/6d8a1060787c2e07d77664b1574aab5ebcde2d2a I pushed a new client stack for zpipes, which uses libzmtp.

The selftest fails in clients/zpipes_client.c:72:

```
int rc = zmtp_dealer_ipc_connect (self->dealer, endpoint);
assert (rc == 0);
```

**Comment by hurtonm** [comment]
I run "make check" and git the following error:
lt-zbroker_selftest: zpipes_server_engine.h:1565: s_server_control_message: Assertion `self->port != -1' failed.
/bin/bash: line 5: 21180 Aborted                 ${dir}$tst
FAIL: zbroker_selftest

Any idea why?

**Comment by hintjens** [comment]
It's doing a socket bind that's failing. You can print out the endpoint,
may be something on your box?

**Comment by hurtonm** [comment]
zmtp_dealer_ipc_connect () fails because there is no one listening on specified endpoint. Please note that libzmtp does not support reconnection so when you created listener after you try to connect, the connect will fail. I may implement reconnect functionality in libzmtp if necessary.

**Comment by hintjens** [comment]
Ah, okay... that helps. Thanks

**Comment by hintjens** [comment]
Have you implemented abstract IPC endpoints? Perhaps this is the problem, since I do start the broker before the client test. The connection is like this:

```
snprintf (endpoint, 255, "ipc://@/zpipes/%s", server_name);
endpoint [255] = 0;
int rc = zmtp_dealer_ipc_connect (self->dealer, endpoint);
assert (rc == 0);
```

The syntax of abstract IPC endpoints comes from libzmq and it's useful because it doesn't create files. I'll test with classic IPC endpoints anyhow.

**Comment by hintjens** [comment]
OK, I've got the connection working. It doesn't accept a 'standard' endpoint, i.e. with "ipc://", rather it expects a pathname.
