### ISSUE TITLE
Problem: libzbroker_cli has artificial deps on czmq 

### ISSUE THREAD

**Issue by rpedde** [zeromq/zbroker#71]
When trying to build a "light" client that only uses libzbroker_cli, there are compile-time deps on czmq.h (prelude, really) for "CZMQ_EXPORT" and "bool".

Probably these should be more self-contained.

**Comment by hintjens** [comment]
I've removed the use of CZMQ_EXPORT. bool and other things we need are defined in zmtp_prelude.h, which should be installed as part of libzmtp, and included with <zmtp.h>
