### ISSUE TITLE
Problem: need config for af_unix perms

### ISSUE THREAD

**Issue by rpedde** [zeromq/zbroker#75]
fixed path /tmp/zpipes-%s with fixed permissions and lack of mode settings makes multi-user access problematic.

**Comment by hintjens** [comment]
Yes, this due to https://github.com/zeromq/libzmtp/issues/31, which we'll
fix asap. I'd suggest using abstract IPC rather than /tmp. Current use of
/tmp is a workaround.

**Comment by rpedde** [comment]
Yeah, I saw the upstream issue, just wanted to hang it here too in order to keep track of it.  Thanks.

**Comment by rpedde** [comment]
confirm works.  thanks.
