### ISSUE TITLE
Problem: zyre sometimes goes crazy.  O_o

### ISSUE THREAD

**Issue by rpedde** [zeromq/zbroker#79]
I've only seen this on multihomed boxes, but sometimes zyre starts pumping out scads of broadcasts:

https://gist.github.com/willkelly/08843595e7cc9e9bfcf8
https://gist.github.com/willkelly/6618d793a822b32624b6

**Comment by rpedde** [comment]
If you are going to disconnect pipes on server disconnects, this will be an issue.  Several times I've seen where a server appears and disappears around 1500 times a second.  When this happens, the reader/writer handshakes seems to fail.

**Comment by hintjens** [comment]
Yes.... Have to fix that zyre issue first...

**Comment by rpedde** [comment]
After the reader/writer handshake confusion, this seems to be the most common problem

**Comment by hintjens** [comment]
I've added tracing to Zyre to debug the issue, and unpinned the Zyre version in zbroker/.travis.yml. For the reader/writer confusion I have pushed a plausible solution. 

All waiting on merges now :-)

**Comment by rpedde** [comment]
reader/writer seems to have fixed it.  I'll rebuild off trunk zyre and get you better zyre storm logs.

**Comment by willkelly** [comment]
I've got extended logs of the behavior here: https://gist.githubusercontent.com/willkelly/64fc56d206db9e5f2d44/raw/gistfile1.txt

**Comment by hintjens** [comment]
Thanks, that's really helpful.

**Comment by hintjens** [comment]
Fixed in Zyre, as far as I can tell. Took a while to hunt down.

**Comment by hintjens** [comment]
Can we close this? I think it's fixed.

**Comment by willkelly** [comment]
Sorry, Pieter!  We have been at the openstack summit and were unable to test.  We'll test today.

**Comment by hintjens** [comment]
No problem. Any issues you hit, let me know... :-)

**Comment by rpedde** [comment]
I'll close it, and make a new one if it comes back.
