### ISSUE TITLE
Problem: need to control what interface broker is active on

### ISSUE THREAD

**Issue by rpedde** [zeromq/zbroker#81]
In a multihomed environment, it would be useful to be able to specify the interface traffic used.

**Comment by hintjens** [comment]
Would this be for Zyre interconnects?

**Comment by rpedde** [comment]
I don't mind zyre over multiple interfaces, but I want to strongly control what interface the pipe traffic flows on.  I have systems with 1GbE interfaces for management, and 10GbE interfaces for cluster traffic.  I'd like the traffic over the 10GbE bonds.
