### ISSUE TITLE
Feature request: longer pipe name in logs

### ISSUE THREAD

**Issue by rpedde** [zeromq/zbroker#88]
I tried to edit the gsl to do this, but the the generated code didn't compile - I think the gsl in zproto doesn't match the zproto that was used to generate the zpipes_server_engine.h and zpipes_server.h.  Can you take a quick look at this?

The underlying problem I was trying to fix was that the pipe name truncation is a bit small.

**Comment by hintjens** [comment]
OK, pushed a fix for this.
