### ISSUE TITLE
Problem: strange zyre_uuid

### ISSUE THREAD

**Issue by rpedde** [zeromq/zbroker#90]
started up a zbroker on a busy cluster and got this:

```
zbroker service/0.0.2
Copyright (c) 2014 the Contributors
This Software is provided under the MPLv2 License on an "as is" basis,
without warranty of any kind, either expressed, implied, or statutory.

14-05-22 16:20:33 I: starting zpipes broker using config in '/tmp/tmp1TDl9n/zbroker.cfg'
14-05-22 16:20:33 I: joining cluster as ENTER
14-05-22 16:20:33 N: starting zpipes_server service
```

This seems odd.  :P

**Comment by hintjens** [comment]
OK, it's caused by mixing data and commands on a single channel from backend Zyre actor to front-end API. What I'll do is create a second channel for data, so that there's no cause for confusion.

**Comment by hintjens** [comment]
Logged in Zyre as https://github.com/zeromq/zyre/issues/191

**Comment by hintjens** [comment]
Fixed by https://github.com/zeromq/zyre/pull/192, theoretically.

**Comment by rpedde** [comment]
will re-open if seen again.
