### ISSUE TITLE
problem: zbroker doesn't compile

### ISSUE THREAD

**Issue by rpedde** [zeromq/zbroker#94]
zlog_new() changes cause:

zpipes_server_engine.h: In function 's_server_new':
zpipes_server_engine.h:1407:5: error: too few arguments to function 'zlog_new'
/tmp/bundler-A1H33SxZqFR/zvm2-zpipes-00053/include/zlog.h:25:5: note: declared here

**Comment by hintjens** [comment]
That change has been reverted.
