### ISSUE TITLE
problem: zyre doesn't log to syslog

### ISSUE THREAD

**Issue by rpedde** [zeromq/zbroker#95]
I've had issues where it seems that brokers are losing each other, as pipes ends don't connect or see reader/writer messages for the appropriate pipe.  It appears that they are getting dropped from discovery, but I can't tell, as zyre is not logging to syslog.

It would be helpful if it were to do so.

**Comment by hintjens** [comment]
Partially fixed by https://github.com/zeromq/zyre/pull/205. This is a substantial change and needs the matching libzmq and czmq masters. Now all logging, up the entire stack, is sent to the same destination.

More work in zpipes to use this properly...

**Comment by hintjens** [comment]
I'm closing this: all logging is now sent via zsys, in CZMQ and Zyre. We can add more logging if needed.
