### ISSUE TITLE
feature request: dump server state

### ISSUE THREAD

**Issue by rpedde** [zeromq/zbroker#96]
a command-line or other option to dump server state (including but especially the zyre map) would be helpful to diagnose problems.

**Comment by hintjens** [comment]
OK, zyre has this now in its API. How should we make this available from the command line? I can see three options:
- broadcast a DUMP request to the entire Zyre cluster so every node logs its state
- extend the pipe protocol and make this a client option (ugly as it crosses layers)
- make a custom command-line tool for diagnosing a zyre instance
